version: "3.9"

services:
    web:
        image: caddy
        restart: unless-stopped
        user: 1000:1000
        networks:
            - craftcms
        volumes:
            - $PWD/app:/var/www
            - $PWD/caddy/Caddyfile:/etc/caddy/Caddyfile
            - caddy_data:/data
        ports:
            - 8080:80

    craftcms:
        image: craftcms:latest
        build: .
        restart: unless-stopped
        user: 1000:1000
        networks:
            - craftcms
        volumes:
            - ./app:/var/www
        ports:
            - 9000:9000

    postgres:
        image: postgres
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          PGDATA: /var/lib/postgresql/data/pgdata
        networks:
          - craftcms
        ports:
          - 5432:5432
        volumes:
          - ./scripts/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
          - db01:/var/lib/postgresql/data

volumes:
    db01:
        driver: local
    caddy_data:
        driver: local

networks:
    craftcms:
        name: craftcms

